### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by ghost** [SYCKGit/imgflip.py#1]
Hi, i tried your package but it won't work because there's missing attribute:

imgflip_client = imgflip.Imgflip(username="Kexotv", password="password", session=requests.Session())
AttributeError: module 'imgflip' has no attribute 'Imgflip'

I am using pyhon 3.9.9 on windows 10

**Comment by SYCKGit** [comment]
works for me... are you sure you installed the right library?
![image](https://user-images.githubusercontent.com/69903990/151698348-c536de29-03ff-4594-aeb6-324f7b91b81b.png)

**Comment by ghost** [comment]
Now, i have second error:
![image](https://user-images.githubusercontent.com/55331891/151715810-9b5918b7-6c2b-4418-b7fb-c675b99ae915.png)

**Comment by SYCKGit** [comment]
You are supposed to define `templates`, as shown in the example
![image](https://user-images.githubusercontent.com/69903990/151736967-714d0499-9b27-4e41-a49c-ae52d32623c1.png)

**Comment by ghost** [comment]
Sorry, i somehow accidentaly removed it, now it works

I don't know why but when i installed this package trough PyCharm it gave me attribute error and when i installed package trough pip cmd it fixed the problem

After testing it, i discovered it has limit - memes that are in this line are maximum i can use? Because i wanted one meme that is on 298 position of templates and it gave me KeyError
![image](https://user-images.githubusercontent.com/55331891/151832184-e3cb1b53-859d-44a6-8ccb-e116faf02030.png)

**Comment by SYCKGit** [comment]
In the example, it gets the top 10 popular memes.
If you want to make a meme on another template, you can just provide the template id in `make_meme`.
![image](https://user-images.githubusercontent.com/69903990/151970288-fe019df3-7813-429a-84ad-2a3a39c27d96.png)
[docs](https://imgflip.readthedocs.io/en/latest/reference.html#imgflip.Imgflip.make_meme)

You can find the template id on the page which shows the blank template.
For example for [Drake Hotline Bling](https://imgflip.com/memetemplate/Drake-Hotline-Bling)
![image](https://user-images.githubusercontent.com/69903990/151971448-02eceb63-4bbd-4118-aa4f-f022e7fdf0e0.png)

**Comment by ghost** [comment]
Now i understand it and it works perfectly, thanks for helping!
